### PR TITLE
Adapters that work

### PR DESCRIPTION
**Pull request by remiolsen**
A little bit of silliness on my part. Of course the adapters in `TrueSeq3_adapters.fasta` will work for HiSeq 2500.

Output from Trimmomatic old vs. new adapters on undisclosed and downsampled HiSeq 2500 sequenced data:
```
Both Surviving: 266821408 (97.25%) Forward Only Surviving: 6096972 (2.22%) Reverse Only Surviving: 1049368 (0.38%) Dropped: 387342 (0.14%)

Both Surviving: 48610 (97.22%) Forward Only Surviving: 1140 (2.28%) Reverse Only Surviving: 171 (0.34%) Dropped: 79 (0.16%)
```

### CODE REVIEW

**Comment by vezzi** [comment]
@remiolsen to double check I understand correctly: we can use `TrueSeq_adapters.fasta` for both HiSeq2500 and HiSeqX right?

**Comment by remiolsen** [comment]
@senthil10 I was unsure of what the best thing to do is. Delete `TrueSeq3` or `TrueSeq`, or keep both? 
`TrueSeq3` is mentioned in our documentation, so that would have to be revised.

@vezzi It looks like it yes. If you want me to do any more testing, let me know.

**Comment by senthil10** [comment]
@remiolsen : Let me see if I got it right, so `TrueSeq3_adapters.fasta` works for both without making any changes and `TrueSeq_adapters.fasta` will work for both with this new change. So now the question is we can remove either of it and change the document accordingly :thinking: 

Well @vezzi , what do you think 😅

**Comment by remiolsen** [comment]
@senthil10 Exactly! The reason why this seems to work is because the sequence `>TruSeq3_UniversalAdapter` is the reverse complement of the old sequence `>TrueSeq_universal_adapter` (minus some parts). And of course PE1 and PE2 are the same.

**Comment by vezzi** [comment]
Ok so my suggestion is:
 - keep only `resources/TrueSeq_adapters.fasta` and remove `TrueSeq3_adapters.fasta ` 

so that there is no longer confusion. would be great if @kate-v-stepanova can test this on the project she is re-running

**Comment by remiolsen** [comment]
@vezzi Done!

**Pull request merged**
